<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework> <!-- 也可以改为 net10.0 -->
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <PublishAot>true</PublishAot>

    <OutputType>Library</OutputType>
    <NoWarn>$(NoWarn);CA2022;SYSLIB0011</NoWarn>

  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../LibSE/LibSE.csproj" />
    <PackageReference Include="SkiaSharp" Version="3.119.4-preview.1.1" />
    <PackageReference Include="SkiaSharp.NativeAssets.macOS" Version="3.119.4-preview.1.1" />

  </ItemGroup>


</Project>

